# Generated by Django 3.0.7 on 2021-10-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=254, unique=True)),
                ('zone_describe', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pincode',
            name='zoneid',
            field=models.IntegerField(default='1', null=True),
        ),
    ]
