# Generated by Django 3.0.7 on 2021-09-03 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shravanmanagement', '0003_task_category_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_parents',
            old_name='dob',
            new_name='age',
        ),
    ]
