# Generated by Django 3.0.7 on 2021-09-06 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shravanmanagement', '0006_auto_20210903_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticketno', models.IntegerField(default=0)),
                ('custname', models.CharField(blank=True, max_length=200, null=True)),
                ('custemail', models.CharField(blank=True, max_length=200, null=True)),
                ('custmobile', models.CharField(blank=True, max_length=20, null=True)),
                ('query_description', models.TextField(blank=True, null=True)),
                ('user_description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('querystatus', models.CharField(choices=[('NOT ATTENDED', 'NOT ATTENDED'), ('IN PROCESS', 'IN PROCESS'), ('CLOSE', 'CLOSE')], default='NOT ATTENDED', max_length=50)),
                ('reqtype', models.CharField(choices=[('SALES', 'SALES'), ('CUSTOMER SUPPORT', 'CUSTOMER SUPPORT')], default='SALES', max_length=50)),
                ('is_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quey_update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
