# Generated by Django 3.0.7 on 2021-10-11 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('shravanmanagement', '0009_task_is_due'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoiceno', models.CharField(blank=True, max_length=200, null=True)),
                ('renewal', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=50, null=True)),
                ('invdate', models.DateField(blank=True, null=True)),
                ('custname', models.CharField(blank=True, max_length=200, null=True)),
                ('custaddr', models.TextField(blank=True, null=True)),
                ('eldersname', models.TextField(blank=True, null=True)),
                ('elderaddr', models.TextField(blank=True, null=True)),
                ('eldercontact', models.TextField(blank=True, null=True)),
                ('custcontact', models.TextField(blank=True, null=True)),
                ('invoicetype', models.CharField(choices=[('Package', 'Package'), ('Non-Package', 'Non-Package')], default='Non-Package', max_length=50, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gstpercentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gstamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('igst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('othercharges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('roundoff', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discountcharge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalcharges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('paymentstatus', models.CharField(choices=[('Not Paid', 'Not Paid'), ('Paid', 'Paid')], default='Not Paid', max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_inv_create', to=settings.AUTH_USER_MODEL)),
                ('cust_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_inv_foreign', to=settings.AUTH_USER_MODEL)),
                ('custcity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.City')),
                ('elderpincode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.Pincode')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_inv_update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
