# Generated by Django 3.0.7 on 2021-10-20 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shravanmanagement', '0010_invoicemanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slotname', models.CharField(blank=True, max_length=200, null=True)),
                ('starttime', models.TimeField(blank=True, null=True)),
                ('endtime', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IcareVisitScheduling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitdate', models.DateField(blank=True, null=True)),
                ('visitstatus', models.CharField(choices=[('Not Visited', 'Not Visited'), ('Visited', 'Visited')], default='Not Visited', max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_vis_create', to=settings.AUTH_USER_MODEL)),
                ('cust_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custforeignkey', to=settings.AUTH_USER_MODEL)),
                ('icare_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icareforeignkey', to=settings.AUTH_USER_MODEL)),
                ('slot_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slotid', to='shravanmanagement.Slots')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_vis_update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
