# Generated by Django 3.0.7 on 2021-10-21 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shravanmanagement', '0011_icarevisitscheduling_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_parents',
            name='adhaarnumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer_parents',
            name='adhaarurl',
            field=models.ImageField(blank=True, default='img/Photos-new-icon.png', null=True, upload_to='parentadhaar/'),
        ),
        migrations.AddField(
            model_name='customer_parents',
            name='profileurl',
            field=models.ImageField(blank=True, default='img/Photos-new-icon.png', null=True, upload_to='parentprofile/'),
        ),
        migrations.AddField(
            model_name='invoicemanagement',
            name='invdescribe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Cust_ID_Proof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passportnumber', models.CharField(blank=True, max_length=200, null=True)),
                ('passporturl', models.ImageField(blank=True, default='img/Photos-new-icon.png', null=True, upload_to='custpassport/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cust_proof_create', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cust_proof_update', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
