# Generated by Django 3.0.7 on 2021-10-24 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shravanmanagement', '0013_auto_20211023_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemanagement',
            name='numberofmonths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoicemanagement',
            name='numberofvisits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoicemanagement',
            name='plantype',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Non-Package', 'Non-Package')], default='Non-Package', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoicemanagement',
            name='preferedday',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invoicemanagement',
            name='preferedweek',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoicemanagement',
            name='slotid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icareslot', to='shravanmanagement.Slots'),
        ),
    ]
