# Generated by Django 3.0.7 on 2021-10-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shravanmanagement', '0016_invoicemanagement_icareid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemanagement',
            name='cgst',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoicemanagement',
            name='discountcharge',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoicemanagement',
            name='gstamount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoicemanagement',
            name='gstpercentage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoicemanagement',
            name='igst',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoicemanagement',
            name='numberofmonths',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoicemanagement',
            name='numberofvisits',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoicemanagement',
            name='othercharges',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoicemanagement',
            name='preferedday',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='invoicemanagement',
            name='roundoff',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoicemanagement',
            name='sgst',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoicemanagement',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoicemanagement',
            name='totalcharges',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
