# Generated by Django 3.0.7 on 2021-11-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shravanmanagement', '0018_pendingtasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingtasks',
            name='created_by',
        ),
    ]
