# Generated by Django 3.0.7 on 2021-11-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shravanmanagement', '0020_pendingtasks_taskstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='icarevisitscheduling',
            name='custparentaddr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icarevisitscheduling',
            name='custparentname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
