# Generated by Django 3.0.7 on 2021-09-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shravanmanagement', '0002_auto_20210831_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_category',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
