# Generated by Django 3.0.7 on 2021-09-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shravanmanagement', '0004_auto_20210903_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='profilepic',
            field=models.ImageField(blank=True, default='img/Photos-new-icon.png', null=True, upload_to='icareproof/'),
        ),
    ]
