# Generated by Django 3.0.7 on 2021-09-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shravanmanagement', '0007_customer_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_request',
            name='ticketno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
