# Generated by Django 3.0.7 on 2021-11-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shravanmanagement', '0019_remove_pendingtasks_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtasks',
            name='taskstatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=50, null=True),
        ),
    ]
